plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.vf6.mediamap'
    compileSdk = 36

    defaultConfig {
        applicationId = 'com.vf6.mediamap'
        minSdk = 28
        targetSdk = 36
        versionCode = 5
        versionName = '1.2.0'
    }

    buildTypes {
        release {
            minifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation files('libs/aauto.aar')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core:1.17.0'
    implementation 'org.osmdroid:osmdroid-android:6.1.20'
}
